#!/bin/csh -f

unlimit

switch ($#argv)
  case "1":
        breaksw
  default:
        echo 'Usage: dna_dump ACEDB_directory' ; exit 1
endsw


cdhttp://www.acedb.org/Software/whelp/Giface.html $1

/nfs/disk100/acedb/RELEASE.SUPPORTED/bin.ALPHA_4/giface . >! CHROMOSOMES/dna_dump.log <<EOF
find sequence CHROMOSOME_I
dna -f CHROMOSOMES/CHROMOSOME_I.dna
find sequence CHROMOSOME_II
dna -f CHROMOSOMES/CHROMOSOME_II.dna
find sequence CHROMOSOME_III
dna -f CHROMOSOMES/CHROMOSOME_III.dna
find sequence CHROMOSOME_IV
dna -f CHROMOSOMES/CHROMOSOME_IV.dna
find sequence CHROMOSOME_V
dna -f CHROMOSOMES/CHROMOSOME_V.dna
find sequence CHROMOSOME_X
dna -f CHROMOSOMES/CHROMOSOME_X.dna
EOF

cd CHROMOSOMES
/bin/cat *.dna | /nfs/disk100/wormpub/bin.ALPHA/composition >! composition.all
/usr/local/bin/perl -ne 'if (/(\d+) total/) { $t = $1 ; print $t ; } if (/- (\d+)/) { $t -= $1 ; print " $t\n" ; }' composition.all >! totals

\rm *.dna.gz
/bin/gzip CHROMOSOME_I.dna
/bin/gzip CHROMOSOME_II.dna
/bin/gzip CHROMOSOME_III.dna
/bin/gzip CHROMOSOME_IV.dna
/bin/gzip CHROMOSOME_V.dna
/bin/gzip CHROMOSOME_X.dna





