#!/usr/local/bin/perl 

#This program makes a remakes a exblx file equivalent
#from a camace object for postwise. 
#IT does not calc the frame because postwise does not require it. 
#hopefully postwise will use gff format one day. 
#


        $exec="/nfs/disk100/wormpub/acedb/ace4/bin.ALPHA_4/tace";
        $ENV{'ACEDB'}="/nfs/disk100/wormpub/acedb/ace4/cam";     
        $command=<<EOF;
        Query Find genome_sequence $ARGV[0]
        show -a pep_homol
        quit
EOF
open(textace, "echo '$command' | $exec | ");
while (<textace>) {s/"//g;
    if (/^Sequence\s+:\s+(\S+)/) {$start="yes";$sequence=$1;}
    if (/^Pep_homol\s+(\S+)\s+\S+\s+(\S+)\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)/) {
     
     $gene=$1;
     $score=$2;
     $startq=$3;
     $endq=$4;
     $starts=$5;
     $ends=$6;

     $gene=~/WP:(\S+)\.\d/;$cosmid=$1;
     if ($cosmid ne $ARGV[0]) {print "$score\t(??)\t$startq\t$endq\t$starts\t$ends\t$gene\n";}
}


                 }
