#!/bin/sh
#
# blastndb - for blasting a whole database

[ $# = 2 ] || { echo >&2 "Usage: blastndb <db> <querydb>"; exit 1; }


IFS='
        '

query=$2.seq


gawk < $2 '

BEGIN { 
	first=1;
	db = "'$1'";
	qdb = "'$2'"; 
    }

/>/ {
        if (!first) {
            close("'$query'");

# Only for self-comp            system("setdb '" $tmp"' ");

	system("nice blastn_repeat '"$1 $query"' H=0 V=0 S=130");
        } else {
            first = 0;
        }
    }

    {
        print > "'$query'";
    }


END {
        close("'$query'");
        system("nice blastn_repeat '"$1 $query"' H=0 V=0 S=130");
    }


