#!/usr/local/bin/perl -w

use Getopt::Std;
use vars qw/ $opt_u /;

getopts ("u:");
my $user = $opt_u;

$| = 1;

if ($user eq "") {
    print "No user name provided. You have to supply a user name.\n";
    exit(0);
}
else {
    print "Starting camace as user $user\n";
}


my $db = "/wormsrv1/camace";

open (DISPLAY, 'printenv HOST |');
while (<DISPLAY>) {
    chomp;
    $host = $_;
}
close DISPLAY;

if ($host ne "wormsrv2") {
    print "You can only access camace from wormsrv2\nLog into that machine to run this database\n\n";   
    exit(0);
}

system ("/nfs/disk100/wormpub/ACEDB/bin.ALPHA/xace -tsuser $user -nosplash $db");

exit (0);

