#!/usr/local/bin/perl -w

my $db = "/wormsrv1/camace";

open (DISPLAY, 'printenv HOST |');
while (<DISPLAY>) {
    chomp;
    $host = $_;
}
close DISPLAY;

if ($host ne "wormsrv2") {
    print "You can only access camace from wormsrv2\nLog into that machine to run this database\n\n";   
    exit(0);
}

system ("/nfs/disk100/acedb/RELEASE.DEVELOPMENT/bin.ALPHA_4/xace -nosplash $db");

exit (0);

