#!/usr/local/bin/perl -w

my $db = "/nfs/disk100/wormpub/DATABASES/current_DB";

# commented out as the database path does not require wormsrv2

system ("/nfs/disk100/wormpub/ACEDB/bin_ALPHA/xace $db");

exit (0);

#######################################################################
# Prints help and disappears                                          #
#######################################################################

sub usage {
    exec ('perldoc',$0);
}

__END__

=pod

=head2   NAME - cgcace

=head1 USAGE

=over 4

=item autoace

=back

autoace is a PERL wrapper which opens an xace session to the cgcace 
database.

update_totals mandatory arguments:

=over 4

=item none

=back

update_totals OPTIONAL arguments:

=over 4

=item none

=back

=head1 CRON

=over 4

=item No


=cut

