#!/usr/local/bin/perl -w

my $db = "/nfs/disk100/wormpub/DATABASES/current_DB";

open (DISPLAY, 'printenv HOST |');
while (<DISPLAY>) {
    chomp;
    $host = $_;
}
close DISPLAY;

if ($host eq "wormsrv2") {
    print "Please do not access this database from wormsrv2.  Use another host such as cbi1.  Thank you.\n";
    exit(0);
}

system ("/nfs/disk100/acedb/RELEASE.DEVELOPMENT/bin.ALPHA_5/xace -nosplash $db");

exit (0);

#######################################################################
# Prints help and disappears                                          #
#######################################################################

sub usage {
    exec ('perldoc',$0);
}

__END__

=pod

=head2   NAME - currentWS

=head1 USAGE

=over 4

=item autoace

=back

currentWS is a PERL wrapper which opens an xace session to the last
WS release of the Worm database.

!! You must run this script from wormsrv2 !!

update_totals mandatory arguments:

=over 4

=item none

=back

update_totals OPTIONAL arguments:

=over 4

=item none

=back

=head1 CRON

=over 4

=item No


=cut

