#!/bin/csh -f

unlimit

switch ($#argv)
  case "1":
        breaksw
  default:
        echo 'Usage: dump_links ACEDB_directory' ; exit 1
endsw


cd $1

/nfs/disk100/wormpub/ACEDB/bin_ALPHA/giface . >! /tmp/chrom_dump.log <<EOF

find sequence SUPERLINK_RW1
dna -f /tmp/SUPERLINK_RW1.dna
find sequence SUPERLINK_RW1R
dna -f /tmp/SUPERLINK_RW1R.dna
find sequence SUPERLINK_RW2
dna -f /tmp/SUPERLINK_RW2.dna
find sequence SUPERLINK_RW3A
dna -f /tmp/SUPERLINK_RW3A.dna
find sequence SUPERLINK_RW3B
dna -f /tmp/SUPERLINK_RW3B.dna
find sequence SUPERLINK_RW4
dna -f /tmp/SUPERLINK_RW4.dna
find sequence SUPERLINK_RW5
dna -f /tmp/SUPERLINK_RW5.dna
find sequence SUPERLINK_RWXL
dna -f /tmp/SUPERLINK_RWXL.dna
find sequence SUPERLINK_RWXR
dna -f /tmp/SUPERLINK_RWXR.dna
EOF

cd /tmp
/bin/cat *.dna | /nfs/disk100/wormpub/bin.ALPHA/composition >! composition.all
/usr/local/bin/perl -ne 'if (/(\d+) total/) { $t = $1 ; print $t ; } if (/- (\d+)/) { $t -= $1 ; print " $t\n" ; }' composition.all >! totals

