#!/usr/local/bin/perl

# This script will mail the contents of ~wormpub/analysis/TO_SUBMIT
# to celegans@ebi.ac.uk.
#
#
#
# Steven Jones, 1995, Sanger Centre.


opendir(DIR,'/nfs/disk100/wormpub/analysis/TO_SUBMIT');
@filenames=grep(/\.embl$/,readdir(DIR));
close DIR;
foreach $file (@filenames) {
    print "$file\n";
    $total++;
}

print "\n$total cosmids found in ~wormpub/analysis/TO_SUBMIT\n";
print "\nAll of these will be submitted to celegans\@ebi.ac.uk\n\n";
print "Do you wish to proceed???(y or n)\n\n";

$answer=<STDIN>;
if ($answer ne "y\n") {die "\nSubmission aborted\n";}


open(files, "ls  /nfs/disk100/wormpub/analysis/TO_SUBMIT  |");

while (<files>) {
	chop;
	if (/embl$/) { 
		print "Mailing /nfs/disk100/wormpub/analysis/TO_SUBMIT/$_\n";
		system ("/usr/ucb/Mail celegans\@ebi.ac.uk < /nfs/disk100/wormpub/analysis/TO_SUBMIT/$_");}
}



