#!/bin/sh
#
# exblx2ace_raw - produce ace from an exblx file

[ $# = 2 ] || { echo >&2 "Usage: exblx2ace_raw <Sequence name> <file.exblx>"; exit 1; }

echo "Sequence " $1
cat     $2 | gawk '{print "Homol", db $7, "BlastX", $1, $3, $4, $5, $6}'

sort +6 $2 | gawk '

BEGIN	{ name = "" ; }

{ 
	if ($7 != name)
	{ 
		name = $7

		printf ("\n")
		print "Sequence :", name

		if (NF+0 > 9)  {
			printf ("Title \"")
			for (i = 9 ; i < NF ; ++i) {
				# Get rid of double quotes 
				a = $i
				if (substr(a,1,1) == "\"") a = substr(a,2)
				if (substr(a,length(a),1) == "\"") a = substr(a,1, length(a)-1)
			       	printf ("%s ", a)
			}
			printf ("%s\"\n", $NF)
		}

		split (name, lib, ":")
		print "Library", lib[1], lib[2], $8
		print "Peptide"
	}
	print "Homol", "'$1'", "BlastX", $1, $5, $6, $3, $4
	next;
}'
