#!/bin/csh
#
# exblx2ace - produce ace from an exblx file

switch ($#argv)
  case "1":
        breaksw
  default:
        echo 'Usage: exblx2ace <file.exblx>' ; exit 1
endsw

cat     $1 | exblx2ace1db
sort +7 $1 | exblx2ace2db
