#!/usr/local/bin/gawk -f
# awk script to extract all alignments with score >= 75 or 
#	multiple hits with some score >= 60 from blastx output.
# Creates output lines of form:
#    score  (frame) query_start query_end  db_start db_end  gene_desciptor

BEGIN { score = 0 ; query = 0 ; score = 0 ;

}

{ 
  a = substr($1,1,1) ;
  if (a == ">") {
	if (score >= 75 || num_hits_this_gene > 1)
      	  printf ("%3d  (%s) %6d %6d  %4d %4d   %s\n", \
		  score, frame, q_start, q_end, db_start, db_end, locus) ;
	if (substr($2,length($2)) == ";")
          $2 = substr($2,1,length($2)-1)
	locus = substr($0,2) ; 
	num_hits_this_gene = 0 ;
	query = 0 ;
	count++ ;  
  }
  if ($1=="Score") {
	if (num_hits_this_gene)
      	  printf ("%3d  (%s) %6d %6d  %4d %4d   %s\n", \
		  score, frame, q_start, q_end, db_start, db_end, locus) ;
	score = $3
	if (substr(score, length(score)) == "*") score = substr(score, 1, length(score)-1)
	if (score >= 60)
	  ++num_hits_this_gene ;
	query = 0 ;
  }
  if ($1=="Identities") {
	frame = $NF ;
  }
  if ($1=="Query:") {
	query++;
	if (query == 1) q_start = $2 ;
	q_end = $4 ;
  }
  if ($1=="Sbjct:") {
	if (query == 1) db_start=$2;
	db_end=$4;
  }
}


END {	
  if (query > 0 && (score > 75 || num_hits_this_gene > 1))
  	printf ("%3d  (%s) %6d %6d  %4d %4d   %s\n", \
		score, frame, q_start, q_end, db_start, db_end, locus) ;
}
