#!/usr/local/bin/gawk -f
#


{
	DNA = $5
	pep = $8

        if (prevDNA != DNA) {

                print ""
                print "Sequence", DNA
                prevDNA = DNA
        }

	if ( pep ~ "_" )
	  db = "SP:"
	else if ( pep ~ /\./ )
	  db = "WP:"
	else 
	  db = "PIR:"

	print "Homol", db pep, "BlastX", $1, $3, $4, $6, $7
}
