#!/usr/local/bin/gawk -f
#
# exblx2ace2 - awk script to produce ace lines for the DNA Homol's
# from an exblx file
#

BEGIN	{ name = "" ; }

{ 
	if (!started) {

		if (cosmid == "") { 
			print "Usage: sort +6 .exblx | exblx2ace2 cosmid=<cosmid name>"
			exit
		}

		started = 1
	}


	if ($7 != name)
	{ 
		name = $7

	   	if ( name ~ "_" ) 
		  { db = "SP:"; lib = "SwissProt" }
		else if ( name ~ /\./ ) 
		  { db = "WP:"; lib = "WormPep" }
	      	else 
		  { db = "PIR:"; lib = "PIR" }

		printf ("\n")
		print "Sequence :", db name

		if (NF+0 > 9)  {
			printf ("Title \"")
			for (i = 9 ; i < NF ; ++i) {
				# Get rid of double quotes 
				a = $i
				if (substr(a,1,1) == "\"") a = substr(a,2)
				if (substr(a,length(a),1) == "\"") a = substr(a,1, length(a)-1)
			       	printf ("%s ", a)
			}
			printf ("%s\"\n", $NF)
		}

		print "Library", lib, name, $8
		print "Peptide"
	}
	print "Homol", cosmid, "BlastX", $1, $5, $6, $3, $4
	next;
}
