#!/usr/local/bin/gawk -f
#

#($1 ~ /*.inv/) { name = substr($1,1,length($1)-4) }

($1 == "Score") \
  { score = substr($2,1,length($1)-1)
    if ($4 == "(100%)")
      percent = 100
    else
      percent = substr($5,1,length($5)-2)
    ngap = $(NF-1)
#    printf ("\n%8s  %4d %3d %2d", name, score, percent, ngap)
    printf ("\nInverted %4d %3d %2d", score, percent, ngap)
  }

(NF == 3) \
  { if (substr($1,1,1) == "|")
      next ;
    printf ("   %6d %6d", $1, $3) }
#    if ($1 < $3)
#      file = "invrep.forward"
#    else
#      file = "invrep.reverse"
#    print ">" name " " $1 > file
#    print $2 > file
#  }
	
END { printf ("\n") }
