#!/usr/local/bin/gawk -f
#

($1 == "Score") \
  { score = substr($2,1,length($1)-1)
    if ($4 == "100%")
      percent = 100
    else
      percent = substr($4,1,length($4)-1)
    ngap = $6
#    printf ("\n%8s  %4d %3d %2d", name, score, percent, ngap)
    printf ("\nDirect %4d %3d %2d", score, percent, ngap)
  }

(NF == 3) \
  { if (substr($1,1,1) == "|" || substr($1,1,1) == "=")
      next ;
    printf ("   %6d %6d", $1, $3) }
#    if ($1 < $3)
#      file = "invrep.forward"
#    else
#      file = "invrep.reverse"
#    print ">" name " " $1 > file
#    print $2 > file
#  }
	
END { printf ("\n") }
