#! /bin/csh
# runs blastp on all gene? in current directory, putting results in
# subdirectory blast, filtered to remove header and trailer, and
# creates a joint exbl of the results.

set scripts = /nfs/al/cb0/wormpub/analysis/scripts

if (! -d blast) mkdir blast

foreach i (0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20)
  if (-e gene$i) then
    echo "blasting gene$i"
    pblast gene$i | awk -f $scripts/blastclean.awk >! blast/gene$i.blp
  endif
end

