#!/usr/local/bin/perl
#
# GFF_with_wormpep_accessions
#

#
#
use Ace;

$|=1;

$file   = shift;
$wormdb = "/wormsrv2/autoace";

$db = Ace->connect(-path=>$wormdb) || do { print "Connection failure: ",Ace->error; die();};

open (GFF, "<$file") || die "Can't open GFF file\n\n";
while (<GFF>) {

    next if (/^\#/);
    
    chomp;

    @gff = split (/\t/,$_);
    
    ($gen_can) = $gff[8] =~ /Sequence \"(\S+)\"/; 

    $obj = $db->fetch(Sequence=>$gen_can);
    if (!defined ($obj)) {
        print "Could not fetch sequence '$gen_can'\n";
        next;
    }

    $acc = $obj->Corresponding_protein(1);
    $acc =~ s/WP\://g;

    if ($acc ne "") {
	$acc =~ s/WP\://g;
	print "$_ wp_acc=$acc\n";
    }
    else {  # could be a tRNA
	print "$_\n";
    }
    undef ($acc); 

    $obj->DESTROY();

}
close GFF;
exit(0);

