#!/usr/local/bin/perl
#
# GFF_with_wormpep_accessions
#

#
#
use Ace;

$|=1;

$file   = shift;
$wormdb = "/wormsrv2/autoace";

$db = Ace->connect(-path=>$wormdb) || do { print "Connection failure: ",Ace->error; die();};

open (GFF, "<$file") || die "Can't open GFF file\n\n";
while (<GFF>) {

    next if (/^\#/);
    
    chomp;

    @gff = split (/\t/,$_);
    
    ($gen_can) = $gff[8] =~ /Sequence \"(\S+)\"/; 

    $obj = $db->fetch(Sequence=>$gen_can);
    if (!defined ($obj)) {
        print "Could not fetch sequence '$gen_can'\n";
        next;
    }

    # exceptions WS32
#   if ($gen_can eq "ZK1236R") {print "$_ acc=n/a\n"; next;}  : removed 010927

    $acc = $obj->Corresponding_protein(1);
    $acc =~ s/WP\://g;
    print "$_ acc=$acc\n";

    $obj->DESTROY();

}
close GFF;
exit(0);

