#!/usr/local/bin/perl
#
# GFF_with_accessions
#

# 010927 :  dl : Removed final exception
# 010620 :  dl : Removed execeptions

use Ace;

$|=1;

$file   = shift;
$wormdb = "/wormsrv2/autoace";

$db = Ace->connect(-path=>$wormdb) || do { print "Connection failure: ",Ace->error; die();};

open (GFF, "<$file") || die "Can't open GFF file\n\n";
while (<GFF>) {

    next if (/^\#/);
    
    chomp;

    @gff = split (/\t/,$_);
    
    ($gen_can) = $gff[8] =~ /Sequence \"(\S+)\"/; 

    $obj = $db->fetch(Sequence=>$gen_can);
    if (!defined ($obj)) {
        print "Could not fetch sequence '$gen_can'\n";
        next;
    }

    # exceptions WS32
#    if ($gen_can eq "ZK1236R") {print "$_ acc=n/a\n"; next;}  : removed 010927

    @acc = $obj->DB_info->row();
    
    print "$_ acc=$acc[4] ver=$acc[5]\n";

    $obj->DESTROY();

}
close GFF;
$db->close;
exit(0);

