#!/usr/local/bin/perl


while(<>) {
    /^#Complete/ && last;
}

$line = <>; # eats ---- line

while( <> ) {
    /^Web_Location/ && next;
    /^Database\s+(\S+)\s+(\S+)/ && do {
	$db = $1;
	$acc = $2;
	print "Motif_homol $db:$acc\n"; 
	next ;
    } ;
    print ;
}
