#!/usr/local/bin/perl

$root = "/nfs/disk100/wormpub/analysis/cosmids";

open (CV,"$root/current.versions") || 
    die "can't find current.versions $!\n";

while ( <CV> ) {
    ($dir) = split ;
    if( -e "$root/$dir/wise/halfwise.out" ) {
	if( !-e "$root/$dir/wise/halfwise.ace" || 
	    ( -M "$root/$dir/wise/halfwise.ace" > -M "$root/$dir/wise/halfwise.out"))  {
	    system("halfwise2ace $root/$dir/wise/halfwise.out > $root/$dir/wise/halfwise.ace") &&
		warn("Could not complete halfwise2ace on $dir $!\n");
	}
    }
}

