#!/usr/local/bin/perl
#to parse the output of hmmfs to ace format
#950203
#Steven Jones


if ($#ARGV != 2) {print "usage: hmmfs2ace2 outputfile threshold repeatname\n";}

open (output, "$ARGV[0]");


while (<output>) {




if (/(\S+)\s+(\d+)\s+(\d+)\s+(\d+)\s+(\S+)\s+(\S+)/) {

if ($1 >= $ARGV[1]) {

print "\nSequence $6\n";$i=1;
print "Homol Motif_homol $ARGV[2]  hmmfs.3 $1 $2 $3 $4 $5\n\n";

print "Motif $ARGV[2]\n";
if ($3 > $2) {print "Homol DNA_homol $6  hmmfs.3 $1 $4 $5 $2 $3 \n\n" }
	else {print "Homol DNA_homol $6  hmmfs.3 $1 $5 $4 $3 $2 \n\n" }

		    }


	}
}









