#!/usr/local/bin/perl -w
#
# list_loci_designations
# v 0.1
#
# dl
#
# Usage : list_loci_designations
#

# 010104 v0.1
# 010104 : dl  : PP version


#################################################################################
# Initialise variables                                                          #
#################################################################################

$|=1;
use IO::Handle;
use Getopt::Std;
use lib '/wormsrv2/scripts/';
use Wormbase;


##############################
# Script variables (run)     #
##############################

my $maintainers = "dl1\@sanger.ac.uk krb\@sanger.ac.uk";
my $rundate = `date +%y%m%d`; chomp $rundate;
my $runtime = `date +%H:%M:%S`; chomp $runtime;

$dbdir = "/wormsrv2/autoace";
$tace  = &tace;
$exec = $tace;
$ENV{'ACEDB'}="$dbdir";
$www = "/nfs/WWW/htdocs/Projects/C_elegans/Info/LOCI";


foreach $char (a..z){
  &find_loci($char);
}
exit(0);


###################

sub find_loci{
  $letter = shift ;
  $search = $letter . "*";
  $line = 0;
  # control whether HTML output is printed
  $html = 1;

  print "Searching db with 'Locus $search'\n";
  
  $command=<<EOF;
find Locus $search where Gene
show -a
quit
EOF

  if ($html) {
    open (HTML, ">$www/loci_designations_$letter.shtml") || die "Couldn't open file for writing to\n";
    print HTML "<TABLE CELLPADDING=0 CELLSPACING=1 BORDER=0><TR class=\"violet3\"><TH WIDTH=\"10%\">Locus</TH><TH>Genomic_sequence</TH><TH>Other_sequence</TH></TR><TR><TD>&nbsp</TD><TD>&nbsp</TD>\n";
  }
  
  open (TEXT_ACE, "echo '$command' | $exec  | ") || die "Couldn't connect to tace\n";
  while (<TEXT_ACE>) {
    chomp;
    
    if (/^Locus\s+\:\s+\"(\S+)\"/) {
      $locus = $1;
      &report_loci;
      print "\nLocus $locus\n";
      if ($html) {
	print HTML "</TR>\n";
	if (($line % 2) == 0) { 
	  print HTML "<TR BGCOLOR=\"lightblue\">\n" if ($html);
	}
	else {
	  print HTML "<TR BGCOLOR=\"white\">\n" if ($html);
	}
	$line++;
	print HTML "<TD>$locus</TD>";
      }
      
    }
    
    if (/^Genomic_sequence\s+\"(\S+)\"/) {push (@genomic,$1);}
    if (/^Other_sequence\s+\"(\S+)\"/)   {push (@other,$1);}
    
  }
  close (TEXT_ACE);
  
  &report_loci;
  print HTML "</TR>\n</TABLE>\n" if ($html);
  
}



#############################################################################

sub report_loci {

#    print "Gen " . scalar (@genomic) . " : Oth " . scalar (@other) . "\n";

    
    if (scalar (@genomic) > 1) {
	
	print "Genomic_sequence : ";
	print HTML "<TD>" if ($html);
	foreach $CDS (@genomic) {
	    next if ($CDS eq "");
	    print "'$CDS' ";
	    print HTML "$CDS " if ($html);
	    
	    
	    unless ($CDS =~ (/\./)) {$error .= "=> Invalid systematic gene name [$CDS]\n";}
	    ($clone,$gene) = split (/\./,$CDS);
	    
	    # consistency checks #1 - EST as XREF to gene
	    if ($CDS =~ /^yk/)   {$error .= "=> EST sequence XREF'd\n";}
	    if ($CDS =~ /^cm/)   {$error .= "=> EST sequence XREF'd\n";}
	    if ($CDS =~ /^CEES/) {$error .= "=> EST sequence XREF'd\n";}
	    if ($CDS =~ /^CEMS/) {$error .= "=> EST sequence XREF'd\n";}
	    
	    push (@clone,$clone);
	    push (@gene,$gene);
	
	
	}
	print "\n";

	# consistency checks #2
	
	if (scalar @clone > 2) {
	    $old_clone = "";
	    foreach $clone (@clone) {
		if ($old_clone eq "") {$old_clone = $clone;next;}
		if ($old_clone ne $clone) {$error .= "=> Clone names are discrepent\n";}
		$old_clone = $clone;
	    }
	}
	

	if (scalar @gene > 2) {
	    $old_gene = "";
	    foreach $gene (@gene) {
		next if ($gene eq "");
		$gene =~ s/[a-z]//g;
		if ($old_gene eq "") {$old_gene = $gene;next;}
		if ($old_gene ne $gene) {$error .= "=> Systematic gene names are discrepent\n";}
		$old_gene = $gene;
	    }
	}
	
	print HTML "</TD> " if ($html);
    }
    else {
	print HTML "<TD>&nbsp</TD> " if ($html);
    }
    
    
    if (scalar (@other) > 1) {
	print "Other_sequence   : ";
	print HTML "<TD>" if ($html);
	foreach (@other) {
	    print "$_ ";
	    print HTML "$_ " if ($html);
	}
	print "\n";
	print HTML "</TD> " if ($html);
    }
    else {
	print HTML "<TD>&nbsp</TD> " if ($html);
    }
    

    if ((scalar (@other) > 1) && (scalar (@genomic) < 2)) {
	$error .= "=> No Genomic_sequence identified whilst Other_sequence XREF'd\n";
    }

    unless ($error eq "") {
	print "$error\n";
    }

    @clone   = "";
    @gene   = "";
    @genomic = "";
    @other   = "";
    $error   = "";

} # end of sub 'report_loci'



