#!/bin/csh

switch (`ostype`)
  case "Irix": 
	set prog = ~wormpub/acedb/bin/xace.SGI
	breaksw
  case "SunOS": 
	set prog = ~wormpub/acedb/bin/xace.SUN
	breaksw
endsw

setenv ACEDB `pwd`/acedb
setenv ACEDB_SU
setenv GF_TABLES ~wormpub/BioSW/gf/tables/wormtables

$prog

