#!/bin/csh 

switch (`ostype`)
  case "Irix": 
	set prog = ~wormpub/acedb/ace4/bin.SGI_4/xace
	breaksw
  case "SunOS": 
	set prog = ~wormpub/acedb/ace4/bin.SUN_4/xace
  	breaksw
  case "OSF1":
	set prog = ~wormpub/acedb/ace4/bin.ALPHA_4/xace
	breaksw

endsw

echo "Uncompressing database files"
if (-e ./acedb_4/database/block1.wrm.Z) then
uncompress acedb_4/database/block*.wrm.Z
echo "Uncompressing database files"
endif
setenv ACEDB `pwd`/acedb_4
setenv ACEDB_SU

$prog

compress  acedb_4/database/block*.wrm &

