#!/usr/local/bin/gawk -f
# script used by mkproj

BEGIN	{ print "\\rm proj" ; 
	  print "touch proj"
	  print "\\rm proj.missing" ; 
	  print "touch proj.missing"
	}

(substr($1,1,1) != "#" && NF == 6) \
	{ printf ("if (-d ~%s/%s) then\n", $6, $2)
	  printf ("  echo \"processing %s\"\n", $1)
	  printf ("  cd ~%s/%s\n", $6, $2) 
	  printf ("  mkcon -p %s -v %s -a -o - | ace2fa cosmid=%s >> proj\n", $3, $4, $1)
	  print "else"
	  printf ("  echo \"missing %s\"\n", $1)
	  printf ("  echo \"%s %s\" >> proj.missing\n", $6, $2)
	  print "endif"
	}
