#!/usr/local/bin/perl

while (<>) {
    
    if (/^RA   The C.elegans Sequencing Consortium/) {
	print "RC   The C.elegans Sequencing Consortium.;\n";
	print "RA   none;\n";
    }
    else {
	print "$_";
    }

}

