#!/bin/csh
#
# run on the alliant to check if blastx jobs are still running

switch (`hostname`)
  case "al": 
    breaksw
  default:
    echo 'parbltest should only be run on the alliant'
    exit 1
endsw

ps -x | grep blast | grep -v grep >! tmpps

if ( -z tmpps ) then
  echo 'There are no jobs'
else
  echo 'There are still jobs'
endif

\rm tmpps

ps -x | grep blast | grep -v grep
