#! /bin/csh 
# parblxclean - reintegrates after parblx

switch ($#argv)
  case "1": 
	breaksw
  default: 
	echo 'Usage: parblxclean seqfile' ; exit 2
endsw

if (-d blast) cd blast

pwd

if (! -e ${1}.blast1) then
  echo "Blast results files not found"
  exit
endif

if (-e ${1}.blx) \rm ${1}.blx
touch ${1}.blx

set i = 1

while (1)
  if (-e ${1}.blast$i) then
    cat ${1}.blast$i >> ${1}.blx
    \rm ${1}.blast$i
    \rm ${1}.log$i
    @ i += 1
  else
    break;
  endif
end

exblastx < ${1}.blx >! ${1}.exblx

echo "The full blast output is in blast/${1}.blx"
echo "            a summary is in blast/${1}.exblx"

exit


