#!/usr/local/bin/perl 
#
# getz5 -f 'id organism ' "[swissprot-org:vertebrata]" | $0 - SW: "subphylum vertebrata"
#
# Allows you to enter into acedb certain species informatation;
# Probably a bit weird but it was the most effiecient was of doing it I could find 
#
#
#
open(file,"$ARGV[0]");


while (<file>) {

if (/^ID\s+(\S+)/) {$first=1;push(@ids,$1);$id=$1;}

if (/^OS/ && $first==1) {
		s/^OS\s+//;
		$first=0;
		@line=split(/\s+/,$_);
		foreach $word (@line) {
			if ($word=~/AND/) {last;}
			if ($word=~/\(/) {last;}
			
			$org{$id}=$org{$id}." ".$word;			
			if ($word=~/,/ || $word=~/\./) {last;}

		}
			
}
}



foreach $id (@ids) {

$org{$id}=~s/\.//;
$org{$id}=~s/,//;
$org{$id}=~s/^\s+//;
$org{$id}=~tr/A-Z/a-z/;
$org{$id}=~/(\S)(.+)/;$firstletter=$1;$rest=$2;
$firstletter=~tr/a-z/A-Z/;
$species=$firstletter.$rest;

print "Protein $ARGV[1]$id\nSpecies \"$species\"\n";

print "\nSpecies \"$species\"\n$ARGV[2]\n\n\n";


}
