#!/usr/local/bin/perl -w
#
# pepace2autoace
#
# v 0.1
#
# Usage : pepace2autoace [-options]
#
# This dumps the required classes from pepace for inclusion in autoace
#
###########################################################################################

# v0.1 (010419)
# 000824 : dl  : PP version  


###########################################################################################
# Variables                                                                               #
###########################################################################################

$|=1;
use IO::Handle;
use POSIX qw(:signal_h :errno_h :sys_wait_h);
use Cwd;
use lib '/wormsrv2/scripts/';
use Wormbase;


################################################
# Some variables                               #
################################################

$tace        = "/nfs/disk100/wormpub/ACEDB/bin.ALPHA_4/tace";
$wormbasedir = "/wormsrv2/wormbase";
$configfile  = "/wormsrv2/autoace_config/pepace.config";


################################################
# Avoid filling process table with zombies     #
################################################

$SIG{CHLD} = \&REAPER;
sub REAPER {
  my $pid;
  $pid=waitpid(-1,&WNOHANG);
  $SIG{CHLD}=\&REAPER;
}

################################################
# Parse config file                            
################################################
  
&mknewacefiles;


###############
# hasta luego #
###############
 
exit (0);

################################################
################## SUBROUTINES #################
################################################


#################################################################################
# Erases old acefiles and make new ones                                         #
#################################################################################

sub mknewacefiles {
    open (CONFIG, "<$configfile");
    while (<CONFIG>) {
	s/^\s+//;s/\s+$//;    
	
	next if (/^\#/  || /^$/);            # comments in file

	if (/^P\s+(\S+)\s+(\S+)$/) {
	    $dbname = $1;
	    $dbdir = $2;
	    $targetdir = "$wormbasedir"."/$dbname";
	    $exe = "$tace $dbdir";
	    next;
	}
	
	# nuts and bolts of acefile generation
	# format:  database object criteria
	
	if (/^\S+\s+(\S+)$/) {
	    $object=$1; $criteria="";$criterianoasterisk="";
	} elsif (/^\S+\s+(\S+)\s+(\S+)$/) {
	    $object=$1; $criteria=$2;
	    $criteria=~/(\S+)\*/;
	    $criterianoasterisk=$1;
	} 

	&make_command;

	print "Filename: $filename\n";
	
        print "Command: 'find $object $criteria' in $dbname\n";
	open (TACE,"| $exe");
	print TACE $command;
	close TACE;
	print "Made file $filename\n\n";
	
	&load_into_autoace($filename);
	
    }
    close CONFIG;
}

sub load_into_autoace{

  my $filename = shift;

  my $command=<<END;
pparse $filename
save
quit
END

  print "Loading $filename into autoace\n\n";
  open (TACE,"| $tace -tsuser pepace /wormsrv2/autoace") || die "Couldn't open pipe to autoace\n";
  print TACE $command;
  close (TACE);


}

sub make_command {

  $filename="$targetdir/".$dbname."_".$object.$criterianoasterisk.".ace";
    
$command=<<END;
find $object $criteria
write $filename
quit
END

}



###################################################
# Prints help and disappears                      

sub PrintHelp {
   exec ('perldoc',$0);
}


__END__

=pod

=head1 NAME - pepace2autoace

=head2 USAGE

make_autoace  makes the autoace database in a given directory.

make_autoace  arguments:

=over 4

=item *

-p path_of_database => location of the new autoace directory

=item *

-r => rebuild the database, excluding distribution and CHROMOSOMES (.dna/.gff) files; and/or

=item *

-d => creates only the distribution files; and/or

=item *

-c => creates only the CHROMOSOMES (.dna/.gff) files; and/or

=back
 
Examples:

make_autoace -p /wormsrv2/WS15 -d 
Creates the distribution files of the database in subdirectory /wormsrv2/WS15

make_autoace -p WS15 -rdc
Creates the new database in the WS15 subdirectory of the current path.
Creates the whole database, including distribution and CHROMOSOME files.

make_autoace -p ~wormpub/new_databases/WS15 -r
Creates the new database in the /new_databases/WS15 subdirectory of the ~wormpub user.
Re-create only the database files, not the distribution or the CHROMOSOME files


=back
=cut
















