#!/usr/local/bin/perl

require glob('~sjj/scripts/sanger.pl');


while (<>) {

	if (/^>(\S+)/) {
		$gene=$1;
		$gene=~/(\S+)\./;$cosmid=$1;
		$brief_id=&brief_id($gene);if ($brief_id eq "") {$brief_id="Unknown";}
		($chrome,$pos)=&seq_pos($cosmid);	
		print ">$gene; $brief_id; $chrome ; $pos;\n";
	}	

else {print;}

}


