#!/usr/local/bin/perl
# ReformatSwir: build a DBM database with AC<>OS relations 
# for all the SWIR entries related to an Accession Number
# [ag3 991611, ms2 991119]


use DB_File;
use Fcntl;
use strict;

$|=1;

my $t = &acetime;

my $dir = glob "~wormpub/WORMPEP";
my $db_out="$dir/SWIRid2org_DBM_$t";


my $db_dir = glob "~pubseq/blastdb";

my $file="$db_dir/swir";


undef my %HASH;
undef my %hash;

undef my ($accession , $database , $organism , $embl);


tie (%HASH , 'DB_File' , $db_out , O_RDWR|O_CREAT , 0644 , $DB_HASH) || die "cannot tie\n";

open (INFILE,"cat $file | grep \'>\' |") || die "cannot open $file\n";
while (my $line=<INFILE>) {
  my @desc=split /\s+/,$line;	
  $desc[0] =~ /\>WP/ && do {$hash{$desc[1]}="Caenorhabditis elegans";next;};
  $desc[0] =~ /\>SW/ && do {$hash{$desc[1]}="SWISSPROT";next;};
  $desc[0] =~ /\>TR/ && do {$hash{$desc[1]}="SPTREMBL";next;};
}
close INFILE;

while (($accession,$database) = each(%hash)) {
  chomp $accession;
  chomp $database;	
  if ($database ne "Caenorhabditis elegans") {
    $organism=`/usr/local/pubseq/bin/getz5 -f org \'[$database-acc:$accession]\'`;
    if (($organism eq "") || (!defined ($organism))) {
        $database="SWISSNEW";
        $organism=`/usr/local/pubseq/bin/getz5 -f org \'[$database-acc:$accession]\'`;
        if (($organism eq "") || (!defined ($organism))) {
            $database="SWISSPROT";
            $organism=`/usr/local/pubseq/bin/getz5 -f org \'[$database-acc:$accession]\'`;
        }
    }
    chomp $organism;
    $organism =~ s/OS\s+//g;
    $organism =~ s/\n/ /g;
    $HASH{$accession}=$organism;
  print "Accession: $accession  Organism: $organism\n";
    $accession=$organism=$database="";
  } else {
    $HASH{$accession}=$database;
  print "Accession: $accession  Organism: $database\n";
    $accession=$database="";
  }
  next;
}

untie %HASH;


exit;

sub acetime {
    my ($sec,$min,$hour,$mday,$mon,$year) = localtime(time);
    while ($year >= 100) {$year -= 100;}
    return sprintf ("%02d%02d%02d", $year, ($mon+1), $mday) ;
}

