#!/usr/local/bin/perl
# Script to change the method associated with each gene
# Only two methods will be conserved: provisional and confirmed
# Skips tRNA genes, etc ..

use Ace;
use Getopt::Std;
$|=1;
$file="/nfs/disk100/wormpub/autoace/CHROMOSOMES/TOTAL.real_cosmids";

getopts ('d:');
chomp $opt_d;

$HELP=<<END;
RetrieveAllAccnos will retrieve all the
  accession numbers associated with cosmids
  RetrieveAllAccnos -d dbname
  dbname will be one of the following: cgcace, autoace, camace
END
  
  if (!$opt_d){
    print $HELP;
  }

# cgcace => port 210203
# autoace => port 210202
# camace => port 100100

if ($opt_d =~ /cgcace/) {
  $db = Ace->connect(-host=>'wormsrv1',-port=>'210203') or die ("Can not connect with database $opt_d on port 210203\n");
}
elsif ($opt_d =~ /autoace/) {
  $db = Ace->connect(-host=>'wormsrv1',-port=>'210202') or die ("Can not connect with database $opt_d on port 210202\n");
}
elsif ($opt_d =~ /camace/) {
  $db = Ace->connect(-host=>'wormsrv1',-port=>'100100') or die ("Can not connect with database $opt_d on port 100100\n");
} else {
  print "Sorry - $opt_d is not a recognized database\n";
}
print "Database $opt_d successful\n\n";

# Retrieve all the Genome sequences from database

$i = $db->fetch_many(Genome_sequence,"*");  
while ($obj = $i->next) {
  $project = $obj;
  $seqname = ($project);
  $dbaccno = $project->at('DB_info.Database[3]');
  if (!$dbaccno) {
  print "## Warning: $seqname does not have accession no\n";
    next;
  }
#  print "** $seqname has AccNo $dbaccno\n";
  
  # Grep the corresponding line from the TOTAL file
  
  open (GREP,"/bin/grep \'\"$seqname\"\' $file |") or (print "Could not grep $seqname\n");
  $TEST{$seqname}="NULL";
  while ($line=<GREP>) {
    if ($line =~ /(CHROMOSOME_\w+)\s+Sequence\s+(\d+)\s+(\d+)\s+\.\s+([+-])\s+/) {
      $TEST{$seqname} =  "$1\tStart: $2\tEnd: $3\tStrand: $4\tSeqname: $seqname\tAccno: $dbaccno";
    }
  }
  close GREP;

# Completely skip if we don't hve the correct coordinates

  if ($TEST{$seqname} =~ /NULL/) {
    print "## Warning: $seqname is not present in the file ##\n";
    next;
  }
  
  # Retrieve the SV from getz
  
  $SV="NA";
  open (GETZ,"getz -f SV \'[emblnew-AccNumber:$dbaccno]\' |");
  while ($getzline=<GETZ>) {
    if ($getzline =~ /SV/) {
      $SV = $getzline;
    }
  }  
  close GETZ;
  
  if ($SV eq "NA") {
    open (GETZ2,"getz -f SV \'[embl-AccNumber:$dbaccno]\' |");
    while ($getzline2=<GETZ2>) {
      if ($getzline2 =~ /SV/) {
	$SV = $getzline2;
      }
    }
  }
  chomp $SV;
  $SV =~ s/\s+/ /;
  print "$TEST{$seqname}\t$SV\n";

} # End while obj ..
  
print "RetrieveAllAccnos FINISHED \n\n";

exit(0);
