#!/usr/local/bin/perl
#
#950207
#Steven Jones
#
#
# Searches fasta format sequences using executables determined in 
# the lookup table and outputs in acefile format
#
# Was specifically written for handling the programs hmmfs and scan
#
#
#NOTE: aceparser must function as: aceparser output threshold repeatname
#
#look-up table format is 
#REPEAT          MODEL     THRESHOLD    ACEFILE-PARSER   EXECUTABLE
#
#


@user=getpwnam(wormpub);
#two environment variables need to be declared
$ENV{MODELDIR} = "$user[7]/analysis/Repeat_Families/CeRep_models";
$ENV{PRIORDIR} = "$user[7]/analysis/Repeat_Families/CeRep_models";


if ($#ARGV != 1) {print "usage:  Search_Repeat_Families  fasta_file  look-up_table\n";exit}

open (lookup, "$ARGV[1]");

while (<lookup>)

{
s/^\s+//; 
if ( /^#/ || /^\n/ || /^$/) {next;}

	else {

		
		/(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(.+)\n/;

		$repeat_type=$1;
		$model=$2;
		$threshold=$3;
		$executable=$5;
		$aceparser=$4;


	system ("$executable $model $ARGV[0] | $aceparser - $threshold $repeat_type"); 




		}




}
