#!/usr/local/bin/perl
#
# shatter fasta file into separate sequences
#
# Usage : shatter <filename> <No. of entries per output file> <name for output files>
#

use strict;

my $file = shift;
my $bin_size = shift;
my $output_name = shift;
my $count = 0;
my $output_count = 1;
my $line;

print "trying to shatter $file in to $bin_size called $output_name\n";

open (OUTPUT, ">${output_name}_${output_count}") || die "can't open file ${output_name}_${output_count} :$! \n" ;

open (FILE, "<$file") or die "cant open $file :$!\n";
while (<FILE>) {
    $line = $_;

    if (/^>(\S+)/) {

	if ($count == $bin_size) {
	    close OUTPUT;

	    $output_count++;

	    open (OUTPUT, ">${output_name}_${output_count}") || die "can't open file ${output_name}_${output_count} :$!\n" ;

	    $count = 0;
	}
	$count++;
    }
    print OUTPUT;
}
close FILE;

close OUTPUT;
