#!/usr/local/bin/perl -w

my $db = "/wormsrv2/stlace";

open (DISPLAY, 'printenv HOST |');
while (<DISPLAY>) {
    chomp;
    $host = $_;
}
close DISPLAY;

if ($host ne "wormsrv2") {
    print "You can only access stlace from wormsrv2\nLog into that machine to run this database\n\n";   
    exit(0);
}

system ("/nfs/disk100/wormpub/ACEDB/bin_ALPHA/xace $db");

exit (0);

