#!/usr/local/bin/perl
#
# stripfiles
# v 0.1
#
# dl
#
#
#
#

#################################################################################
# variables                                                                     #
#################################################################################

$|=1;
use IO::Handle;
use Getopt::Std;
use Cwd;
require "/nfs/disk100/wormpub/analysis/scripts/babel.pl";

 ##############################
 # Script variables (run)     #
 ##############################

my $maintainer = "dl1\@sanger.ac.uk";
my $rundate    = `date +%y%m%d`; chomp $rundate;
my $runtime    = `date +%H:%M:%S`; chomp $runtime;
my $logfile    = "/wormsrv2/logs/stripfiles.$rundate.$$";
my $version    = &get_script_version("stripfiles");

 ##############################
 # Paths for I/O files        #
 ##############################

my $dbdir   = "/wormsrv2/stlace";
my $tace    = "/nfs/disk100/acedb/RELEASE.DEVELOPMENT/bin.ALPHA_4/tace";
my $giface  = "/nfs/disk100/acedb/RELEASE.DEVELOPMENT/bin.ALPHA_4/giface";

my @filenames = "";
my $filename  = "";

 ##############################
 # command-line options       #
 ##############################

$opt_h = "";   # Help/Usage page
$opt_r = "";   # Release date of database.tar.gz files

getopts ('hr:');
&usage if ($opt_h);


 ##############################
 # open logfile               #
 ##############################

#system ("/bin/touch $logfile");
#open (LOGFILE,">>$logfile");
#LOGFILE->autoflush;

#print LOGFILE "# unpack_stlace\n#\n";
#print LOGFILE "# version             : $version\n";
#print LOGFILE "# run details         : $rundate $runtime\n";
#print LOGFILE "# Source directory    : $ftp\n";
#print LOGFILE "# Target directory    : $dbdir\n#\n";
#print LOGFILE "# Source file         : stlace_$today.tar.gz\n";
#print LOGFILE "\n";


#
# Protein .acefile
#
 
$acefile = "stlace_Protein";
$/ = "Protein :";

open (OUT, ">${acefile}_test.ace");
open (FILE, "<${acefile}.ace");
while (<FILE>) {
    
    if (/\"WP:/) {
	next;
    }
    else {
	print OUT "$_";
    } 
}
close FILE;
close OUT;
$/ = "\n";


#
# Sequence .acefile
#

$acefile = "stlace_Sequence";

open (OUT, ">${acefile}_test.ace");
open (FILE, "<${acefile}.ace");
while (<FILE>) {
    
    if (/\"WP:/) {
	next;
    }
    else {
	print OUT "$_";
    } 
}
close FILE;
close OUT;
exit(0);
