#!/usr/local/bin/perl 
#
# Script to get annotation, locus and EC number from swiss prot. 
# for camace genes. 
#

@genes=&getcds; 

foreach $gene (@genes) {
	$geneuppercase=$gene;$geneuppercase=~tr/a-z/A-Z/;

	open(swiss,"getz5 -f \"des gen\" \"[swissnew-gen:$gene] \| ([swissprot-gen:$gene] \! [swissnew-gen:$gene] < swissnew)\" |");
	
	$des="";
	$locus="";
	$ec="";

	while (<swiss>) {s/\.$//;
		if (/^DE\s+(.+)/) {if ($des ne "") {$des=$des." ".$1;} else {$des=$1;}}

		#look for locus definitions 
		#assume that in swiss prot the format is always  UNC-22 OR ZK554.4 with the locus 
		#first. Also, need to get rid of some of the brackets.
		if (/^GN/) {s/\)//;s/\(//;}
		if (/(\S\S\S\-\d+)\s+OR\s+(\S+)/ && $2 eq $geneuppercase) {$locus=$1;}
	}
	close swiss;

        #get multiple  EC numbers out the description line
	$found=1;
	$tempdes=$des;
	undef @ecs;
	while ($found==1) {
	    if ($tempdes=~/\(EC\s+(\S+\.\S+\.\S+\.\S+)\)/) {push(@ecs,$1);} else {$found=0;}
	$tempdes=~s/\(EC\s+\S+\.\S+\.\S+\.\S+\)//;
	}

	#print out the acefile
	if ($des ne "") {
	    
		print "\nSequence $gene\n";
		#remove any EC_number as the newer version may not have any.
		print "-D EC_number\n";

		print "SwissProt_DE \"$des\"\n";
		if ($locus ne "") {$locus=~tr/A-Z/a-z/;print "locus $locus\n";}
		foreach $ec (@ecs) {print "EC_number $ec\n";}
		print "\n";
	    }
	#I guess to be safe we want to remove annotations for active CDS genes which don't 
	#have an entry in Swiss anymore - does this happen?  
	else {print "\nSequence $gene\n-D EC_number\n-D SwissProt_DE\n\n";} 


	#print out URL info for the EC numbers 
	foreach $ec (@ecs) { 
	    print "\nUrl $ec\n";
	    print "Url \"http:\\/\\/www.expasy.ch:80\/cgi-bin/get-full-entry?[ENZYME-ID:'$ec']\"\n\n";


	}

}

###############################################
#Get a list of the camace cds 
###############################################

sub getcds {
	local(@genes);
	$exec="tace";
	$command=<<EOF;
        find genome_sequence
        follow subsequence 
	where CDS
	where method="hand_built" OR method="genefinder" 
	list -f -
	find genome_sequence 
	follow source
	follow subsequence
	where CDS
	where method="hand_built" OR method="genefinder"
	list -f -	
        quit
EOF
open(textace, "echo '$command' | $exec  /nfs/disk100/wormpub/acedb/ace4/cam | ");
while (<textace>) {if (/Sequence\s+:\s+"(\S+)"/) {push(@genes,$1);}}

return @genes;

}




