#!/usr/local/bin/gawk -f
{
  if (match($6,/\./))
    $6 = substr($6,1,RSTART-1)
# printf ("\nSequence %s\n", $1)
  print "Tandem", $2, $3, "Unit_Length", $4
  print "Tandem", $2, $3, "Score +1-1", $1
  print "Tandem", $2, $3, "Percent_Identity", $6
}
