#!/usr/local/bin/perl

#Convert wormpep into ace format

#Steven Jones, Sanger Centre (requires efetch)



while (<>) {
	if (/^>(\S+)\s+(\S+)\s+/) {
	                $wormpepid=$1;
			$wormpepacc=$2;
			print "\nProtein WP:$1\n";
			print "DB_info Database Wormpep $1 $2\n";
			print "Corresponding_DNA $1\n";
			print "Species \"Caenorhabditis elegans\"\n";
	if (/\s+(SW:\S+)$/) {
			    open(efetch,"efetch -a $1 |");
			    while (<efetch>) {if (/^ID\s+(\S+)/) {$id=$1;}
					      if (/^AC\s+(\S+)/) {$acc=$1;}
						}
			    close efetch;
			    print "DB_info Database SwissProt $id $acc\n";	
			}

	if (/^>\S+\s+\S+\s+(.+)\s+\(CAMBRIDGE\)/ || /^>\S+\s+\S+\s+(.+)\s+\(ST.LOUIS\)/) {
			print "Title \"$1\"\n";			
			}
			print "\n\nPeptide WP:$wormpepid\n";
	} else {print;}

}
