#!/usr/local/bin/perl
# YACtoSecAcc: reassignment of EMBL secondary AccNos. 
# Needs as input two lists of YAC names dumped from Camace
# in the form EMBL:YACID and EMBLNEW:YACID

$|=1;

# Internal confs
my $EMBLNAMES = "/nfs/disk100/wormpub/ag3/ACCNOS/EMBLNAMES";
my $EMBLNEWNAMES = "/nfs/disk100/wormpub/ag3/ACCNOS/EMBLNEWNAMES";

# Retrieve from EMBLNEW internal clones
open (EMBLNEW,"/usr/local/pubseq/bin/getz6 -f ID -f ACC \'\@$EMBLNEWNAMES\'|");
while (<EMBLNEW>) {
  if ($_ =~ /ID\s+(\w+)\s+/) {
    $CLONE=$ID=$1;
    $CLONE =~ s/[A-Z]$//;
    push (@{$CORR{$CLONE}},$ID);
    $FOUND{$ID}="TRUE";
    next;
  } else {
    if ($_ =~ /AC\s+(\w+)\;/) {
      $ACC=$1;
      push (@{$CORR{$CLONE}},$ACC);
      $FOUND{$ACC}="TRUE";
      next;
   }
  }
}
close EMBLNEW;

# Retrieve from EMBL internal clones, non-overlapping with EMBLNEW entries
open (EMBL,"/usr/local/pubseq/bin/getz6 -f ID -f ACC \'\@$EMBLNAMES\'|");
while (<EMBL>) {
  if ($_ =~ /ID\s+(\w+)\s+/) {
    $CLONE=$ID=$1;
    $CLONE =~ s/[A-Z]$//;
    if ($FOUND{$ID}) {
      next;
    } else {
      push (@{$CORR{$CLONE}},$ID);
      $FOUND{$ID}="TRUE";
      next;
    }
  } else {
    if ($_ =~ /AC\s+(\w+)\;/) { 
      $ACC=$1;
      if ($FOUND{$ACC}) {
	next;
      } else {
      push (@{$CORR{$CLONE}},$ACC);
      $FOUND{$ACC}="TRUE";
    }
    }
  }
}
close EMBL;

# For each clone, assign the secondary AccNo as the YAC primary accno.
# Skip the clone names non ending with A.B,C because these are the source of
# primary ACnos.
# Not all the clones have an old YAC name left !
foreach $KEY (sort keys %CORR) {
  $ACCNO=`/usr/local/pubseq/bin/getz6 -f ACC \'[emblnew-ID:$KEY]\'`;
  if (length($ACCNO)<2) {
    $ACCNO=`/usr/local/pubseq/bin/getz6 -f ACC \'[embl-ID:$KEY]\'`;
  }
  if (length($ACCNO)<2) {   
    next;
  } else {
    $ACCNO =~ s/AC//;
    $ACCNO =~ s/\;//;
    $ACCNO =~ s/\s+//mg;
    @clonearray=@{$CORR{$KEY}};
    $index=0;
    for ($arrsize=$#clonearray;$arrsize>0;$arrsize=$arrsize-2) {
      ($ID,$ACC) = splice (@clonearray,0,2);
      print "$ID\n";
#      print "\nSequence  \"$ID\"\n";
#      print "Secondary_accession  $ACCNO\n\n";
    }
  }
}




