#!/bin/bash

ANCIENT_PARASITE_VERSION=$((PARASITE_VERSION - 15))
ANCIENT_ENSEMBL_VERSION=$((ENSEMBL_VERSION - 15))

TEST_PARASITE_VERSION=${PARASITE_VERSION}
TEST_ENSEMBL_VERSION=${ENSEMBL_VERSION}

while [[ $TEST_PARASITE_VERSION -ge $ANCIENT_PARASITE_VERSION && $TEST_ENSEMBL_VERSION -ge $ANCIENT_ENSEMBL_VERSION ]]; do
  TEST_PARASITE_VERSION=$((TEST_PARASITE_VERSION - 1))
  TEST_ENSEMBL_VERSION=$((TEST_ENSEMBL_VERSION - 1))
  CONCATENATED="${TEST_PARASITE_VERSION}_${TEST_ENSEMBL_VERSION}"
  SUFFIX="_${CONCATENATED}_"
  
  if $PARASITE_STAGING_MYSQL -Ne "SHOW DATABASES" | grep -q "_${CONCATENATED}_";
    then echo "Error! Found older databases in your staging server. Please investigate and/or delete";
    $PARASITE_STAGING_MYSQL -Ne "SHOW DATABASES" | grep "_$CONCATENATED_";
  fi;
done